repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: requirements-txt-fixer
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: debug-statements
    - id: check-merge-conflict

- repo: https://github.com/ambv/black
  rev: 22.10.0
  hooks:
  - id: black
    language: python
    types: [python]
    args: ["--line-length=88"]

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    args: ["--max-line-length=88", "--extend-ignore=E203", "--doctests"]

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v14.0.6
  hooks:
  - id: clang-format
    args: ["--style=Google"]
    files: \.(c|cpp|h|cu|cuh)$
